### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Diegonarducci88** [asand3r/zbx_backup#1]
ERROR: Cannot create TAR archive (/tmp/zbx_files_22.11.2017.140427.tar) with data files.

cmd: ./new_backup.sh -c gzip -u root -p **** -n zabbix -m

**Comment by asand3r** [comment]
Hi, I have some questions:
1. Do you use v0.5.2?
2. Have you tried to use --debug option to determine what all setting are OK?
3. Did you run the script with user who can access to '/etc/zabbix' and '/usr/lib/zabbix'?

**Comment by asand3r** [comment]
@Diegonarducci88, it the problem still present?
