### ISSUE TITLE
[Request] Backup config and/or datas tables

### ISSUE THREAD

**Issue by FireHelmet** [asand3r/zbx_backup#2]
Hello @asand3r 

Could you add an option to backup config tables and/or datas tables ? Because when you have crash, you want to restore quickly as possible and make Zabbix up and running and when datas are saved at the same time the time to backup and restore can be very very long...

Thank you !

**Comment by asand3r** [comment]
Hi @FireHelmet. =)
You know, it's interesting idea, so I'll necessarily think how to realize this feature.

**Comment by asand3r** [comment]
@FireHelmet 
Hey, wanna inform you that i've added v0.6.0 in DEV branch, where you can use '-e|--exclude-tables' option to exclude some tables.
The new option has two presets: data and config. The first one is excludes all zabbix data tables and another excludes all other, but keeps data. Also you can set tables list by yourself using space like separator. E.g.:
zbx_backup (some options) -e data
zbx_backup (some options) -e config
zbx_backup (some options) -e "history trends_uint"

Be notices, I've switched to using one option for choosing database backup utility - '-b|--backup-with' (see help, please) instead separate '-x' and '-m' options. They still present, but you can see WARNING message about it's deprecated.
And last, but not least - exclusion works only with mysqldump yet.

**Comment by asand3r** [comment]
Tables exclusion added in v0.6.
